    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html


    spring:
        mvc:
                static-path-pattern: /**
        profiles:
            active: dev

    comment.avatar: /images/cstx.jpg